service: candidate

plugins:
  - serverless-python-requirements
  - serverless-plugin-cloudwatch-dashboard

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: eu-west-1

package:
    exclude:
        - node_modules/**

custom:
  pythonRequirements:
      dockerizePip: non-linux

functions:
  candidate:
    handler: app/candidate.submit
    memorySize: 128
    description: Submit candidate information and starts interview process.
    events:
      - http: 
          path: candidates
          method: post
